### ISSUE TITLE
Initial configuration - no way to save a profile

### ISSUE THREAD

**Issue by mreiger** [MakG10/plasma-applet-display-profile-switcher#1]
Hi! I just downloaded this plasmoid from the KDE store and installed it into the panel.

When I try to configure the app and save my first profile, I can not because the profile screen remains empty; screenshot is attached.

![Screenshot_20201028_094025](https://user-images.githubusercontent.com/47994873/97466493-7583b080-1943-11eb-81f7-d654465d66aa.png)

I am running Kubuntu 20.10, upgraded from 20.04. 
Is there a chance I am missing a dependency?

I am willing to debug, but have no real clue where to start.

**Comment by MakG10** [comment]
Hi, could you run in the terminal:
`journalctl -f | grep --line-buffered eu.makg`
then open the profiles settings and see if there is any output?

**Comment by mreiger** [comment]
No output at all.

However I was able to run the applet in plasmawindowed, this is the output:
```
michael@metalmachine:~/.local/share/plasma/plasmoids$ plasmawindowed eu.makg.plasma.display-profile-switcher/
Qt: Session management error: Could not open network socket
Loading default layout
QObject::disconnect: Unexpected nullptr parameter
kf.plasma.core: requesting config for "Display Screen Profile Switcher" without a containment!
kf.plasma.quick: Applet preload policy set to 1
qml: 0
QQmlComponent: Component is not ready
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/AppletConfiguration.qml:300:25: QML StackView: replace: file:///home/michael/.local/share/plasma/plasmoids/eu.makg.plasma.display-profile-switcher/contents/ui/config/configGeneral.qml:1 module "QtQuick" version 2.15 is not installed
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/AppletConfiguration.qml:330: TypeError: Cannot read property 'cfg_objectNameChanged' of null
file:///home/michael/.local/share/plasma/plasmoids/eu.makg.plasma.display-profile-switcher/contents/ui/main.qml:32: TypeError: Cannot read property 'configuration' of null
<Unknown File>:1: TypeError: Cannot read property 'Layout' of null
QObject::disconnect: Unexpected nullptr parameter
```

The lines
```
QQmlComponent: Component is not ready
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/AppletConfiguration.qml:300:25: QML StackView: replace: file:///home/michael/.local/share/plasma/plasmoids/eu.makg.plasma.display-profile-switcher/contents/ui/config/configGeneral.qml:1 module "QtQuick" version 2.15 is not installed
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/AppletConfiguration.qml:330: TypeError: Cannot read property 'cfg_objectNameChanged' of null
```
appear when I click on the `configure` button and get the empty Profiles screen.

**Comment by MakG10** [comment]
Hmm maybe I shouldn't have used the most recent version of QtQuick, what version of `qml-module-qtquick-controls` package do you have installed?

Can you try the version on this branch? https://github.com/MakG10/plasma-applet-display-profile-switcher/tree/qtquick_downgrade

I've just downgraded QtQuick there, because it makes no difference in this applet anyway.

You can test it using:
```
git clone https://github.com/MakG10/plasma-applet-display-profile-switcher.git
cd plasma-applet-display-profile-switcher
git checkout qtquick_downgrade
plasmapkg2 -r package && plasmapkg2 -i package && plasmoidviewer -a eu.makg.plasma.display-profile-switcher
```

**Comment by mreiger** [comment]
Yes I think kubuntu is still on Qt 5.14

This version looks good: 
![Screenshot_20201028_181755](https://user-images.githubusercontent.com/47994873/97472408-1b3a1e00-194a-11eb-862a-c09e72370b0e.png)

**Comment by mreiger** [comment]
So I would consider this solved - it works well for me. Thanks a lot!
Maybe you can merge this and push it to store.kde.org?

Do you want to close the issue or should I?

**Comment by MakG10** [comment]
I've merged in to master and will publish on store.kde.org today. Thanks for taking the time to report the issue!
