### ISSUE TITLE
Broken in Plasma 5.23.1+

### ISSUE THREAD

**Issue by Esgariot** [MakG10/plasma-applet-display-profile-switcher#3]
Looks like `org.kde.KScreen /backend` is no longer available, but I can't find the replacement or related changelogs. 

EDIT: Nevermind. It's still there, but there's some other issue.

**Comment by fpontef** [comment]
I use Archlinux and also had some issues while running the python script located at:  ~/.local/share/plasma/plasmoids/eu.makg.plasma.display-profile-switcher/display-profile-switcher.py
It should return an enconded config or something, but instead were returning:
AttributeError: module 'dbus' has no attribute 'SessionBus'

So I tried importing dbus from python and could not get the SessionBus, maybe some glib + dbus + python related? But worked fine after I installed the pacman package: extra/dbus-python 1.2.18-1  described as: Python bindings for DBUS.
